### PR TITLE
Add IORef, MVar and TVar instances

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
CI fails. You need to update the setup-haskell job to v1.1.4

**Comment by edsko** [comment]
Ah, awesome to have a solution that works :) I think `readTVarIO` wasn't available to us. Great :) Thanks! @mrBliss has kindly offered to fix CI :)

**Comment by phadej** [comment]
Rebased

**Review by edsko — APPROVED** [review]
Ah, sorry,  somehow thought @mrBliss would do that, I wasn't waiting for you to do it :) But thanks :) Merging now.

**Comment by expipiplus1** [comment]
Thanks, just wanted this now!

**Comment by expipiplus1** [comment]
Is it possible to get a release with this in, please?

**Comment by edsko** [comment]
Done :)

**Comment by expipiplus1** [comment]
Thank you!

**Pull request merged**
